# -*- coding: utf-8 -*-
"""ShapeAI_PYTHON_NETWORK_SECURITY_PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16vPEBUbzB7OTl5lZeB6zMKbe2PeT60_-

Write a program in Python to generate hashes of string data using 3 algorithms from hashlib
"""

import hashlib

message = "Text to hash".encode()

"""Now, I am going to use different hash algorithms on this message string from hashlib

1. HASH WITH SHA-2 ( SHA-256 & SHA-512)
"""

print("SHA-256:", hashlib.sha256(message).hexdigest())

print("SHA-512:", hashlib.sha512(message).hexdigest())

"""2. HASH WITH SHA- 3 (SHA-3-256 & SHA-3-512)"""

print("SHA-3-256:", hashlib.sha3_256(message).hexdigest())

print("SHA-3-512:", hashlib.sha3_512(message).hexdigest())

"""3. HASH WITH BLAKE2 ( 256-bit BLAKE2 & 512-bit BLAKE2)"""

print("BLAKE2c:", hashlib.blake2s(message).hexdigest())

print("BLAKE2b:", hashlib.blake2b(message).hexdigest())